<?php

//        run "php artisan config:clear" after updating this file
return [


    'permissions' => [
        'Menus_Reception',
        'Menus_Reports',
        'Menus_Accounts',
        'Menus_Settings',
        'Clinics_Access',
        'Clinics_Create',
        'Clinics_Read',
        'Clinics_Update',
        'Clinics_Delete',
        'Users_Access',
        'Users_Create',
        'Users_Read',
        'Users_Update',
        'Users_Delete',
        'Offers_Access',
        'Offers_Create',
        'Offers_Read',
        'Offers_Update',
        'Offers_Delete',
        'Departments_Access',
        'Departments_Create',
        'Departments_Read',
        'Departments_Update',
        'Departments_Delete',
        'Doctors_Access',
        'Doctors_Create',
        'Doctors_Read',
        'Doctors_Update',
        'Doctors_Delete',
        'Nurses_Access',
        'Nurses_Create',
        'Nurses_Read',
        'Nurses_Update',
        'Nurses_Delete',
        'Treatments_Access',
        'Treatments_Create',
        'Treatments_Read',
        'Treatments_Update',
        'Treatments_Delete',
        'Nationalities_Access',
        'Nationalities_Create',
        'Nationalities_Read',
        'Nationalities_Update',
        'Nationalities_Delete',
        'AppDepartments_Access',
        'AppDepartments_Create',
        'AppDepartments_Read',
        'AppDepartments_Update',
        'AppDepartments_Delete',
        'AppDevices_Access',
        'AppDevices_Create',
        'AppDevices_Read',
        'AppDevices_Update',
        'AppDevices_Delete',
        'AppStatuses_Access',
        'AppStatuses_Create',
        'AppStatuses_Read',
        'AppStatuses_Update',
        'AppStatuses_Delete',
        'Accounts_Access',
        'Accounts_Create',
        'Accounts_Read',
        'Accounts_Update',
        'Accounts_Delete',
        'Appointments_Access',
        'Appointments_Create',
        'Appointments_Read',
        'Appointments_Update',
        'Appointments_Delete',
        'Patients_Access',
        'Patients_Create',
        'Patients_Read',
        'Patients_Update',
        'Patients_Delete',
        'Invoices_Access',
        'Invoices_Create',
        'Invoices_Read',
        'Invoices_Update',
        'Invoices_Delete',
        'Invoices_Discount',
        'Balances_Access',
        'Balances_Create',
        'Balances_Read',
        'Balances_Update',
        'Balances_Delete',
        'JournalVouchers_Access',
        'JournalVouchers_Create',
        'JournalVouchers_Read',
        'JournalVouchers_Update',
        'JournalVouchers_Delete',
        'BankPayments_Access',
        'BankPayments_Create',
        'BankPayments_Read',
        'BankPayments_Update',
        'BankPayments_Delete',
        'BankReceipts_Access',
        'BankReceipts_Create',
        'BankReceipts_Read',
        'BankReceipts_Update',
        'BankReceipts_Delete',
        'AccountGroups_Access',
        'AccountGroups_Create',
        'AccountGroups_Read',
        'AccountGroups_Update',
        'AccountGroups_Delete',
        'Reports_DayClosing',
        'Reports_DailyIncome',
        'Reports_Appointments',
        'Reports_CollectionStatements',
        'Reports_Accounts',
        'Dashboard_YearlyRevenueChart',
        'Dashboard_PieChart',
        'Dashboard_AppStatuses',
        'Dashboard_UpcomingBirthdays',
        'Dashboard_ErrorVouchers',
        'Dashboard_Offers',
    ],

    'patient_sources' => [
        'Instagram',
        'Facebook',
        'Friend',
        'Old Patient',
        'Other',
    ],


];


